# Generated by Django 2.2.8 on 2020-02-15 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Addresses'},
        ),
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Fruits &Vegtables', 'Fruits &Vegtables'), ('Drinks', 'Drinks'), ('Drinks', 'Beverages'), ('Canned & Packaged food', 'Canned & Packaged food'), ('Grains, Rice and Dried Beans', 'Grains, Rice and Dried Beans'), ('Grains, Rice and Dried Beans', 'Herbs, Spices & Seasoning'), ('Laundry & Household Cleaning', 'Laundry & Household Cleaning'), ('Biscuits an2d Confectionaries', 'Biscuits and Confectionaries'), ('Others', 'Others')], max_length=30),
        ),
        migrations.AlterField(
            model_name='order',
            name='ref_code',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
