# Generated by Django 2.2.8 on 2020-02-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200215_0918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('Fruits &Vegtables', 'Fruits &Vegtables'), ('Drinks', 'Drinks'), ('Drinks', 'Beverages'), ('Meat', 'Meat'), ('Canned & Packaged food', 'Canned & Packaged food'), ('Grains, Rice and Dried Beans', 'Grains, Rice and Dried Beans'), ('Grains, Rice and Dried Beans', 'Herbs, Spices & Seasoning'), ('Laundry & Household Cleaning', 'Laundry & Household Cleaning'), ('Biscuits an2d Confectionaries', 'Biscuits and Confectionaries'), ('Others', 'Others')], max_length=30),
        ),
    ]
